# Generated by Django 5.2.7 on 2025-12-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(max_length=20, unique=True, verbose_name='ID в HH')),
                ('name', models.CharField(max_length=500, verbose_name='Название вакансии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(blank=True, max_length=10, verbose_name='Валюта')),
                ('employer_name', models.CharField(blank=True, max_length=300, verbose_name='Работодатель')),
                ('employer_id', models.CharField(blank=True, max_length=20, verbose_name='ID работодателя')),
                ('area_name', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('area_id', models.CharField(blank=True, max_length=20, verbose_name='ID города')),
                ('experience', models.CharField(blank=True, max_length=100, verbose_name='Опыт работы')),
                ('schedule', models.CharField(blank=True, max_length=100, verbose_name='График работы')),
                ('employment', models.CharField(blank=True, max_length=100, verbose_name='Тип занятости')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на вакансию')),
                ('requirement', models.TextField(blank=True, verbose_name='Требования')),
                ('responsibility', models.TextField(blank=True, verbose_name='Обязанности')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['hh_id'], name='vacancies_v_hh_id_a982a0_idx'), models.Index(fields=['name'], name='vacancies_v_name_07c2b1_idx'), models.Index(fields=['area_name'], name='vacancies_v_area_na_404099_idx')],
            },
        ),
    ]
