# Generated by Django 5.2.7 on 2025-12-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employer_logo_url',
            field=models.URLField(blank=True, verbose_name='Логотип работодателя'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='professional_role',
            field=models.CharField(blank=True, max_length=200, verbose_name='Категория профессии'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['professional_role'], name='vacancies_v_profess_25d034_idx'),
        ),
    ]
